<?php
require_once __DIR__.'/../common/config.php';require_admin();$id=(int)($_GET['id']??0);$s=$pdo->prepare("SELECT * FROM tournaments WHERE id=?");$s->execute([$id]);$t=$s->fetch();if(!$t)exit('Tournament not found.');
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();$action=$_POST['action']??'';if($action==="tournament_room"){$pdo->prepare("UPDATE tournaments SET room_id=?,room_password=? WHERE id=?")->execute([post_string("room_id"),post_string("room_password"),$id]);flash("success","Room details saved.");}elseif($action==="start"){$pdo->prepare("UPDATE tournaments SET status='live' WHERE id=?")->execute([$id]);flash('success','Tournament started.');}elseif($action==='rooms'){$s=$pdo->prepare("UPDATE participants SET room_id=?,room_password=? WHERE tournament_id=? AND user_id=?");$s->execute([post_string('room_id'),post_string('room_password'),$id,(int)$_POST['user_id']]);flash('success','Room details updated.');}elseif($action==='complete'){$winner=(int)$_POST['winner_id'];try{$pdo->beginTransaction();$s=$pdo->prepare("SELECT * FROM participants WHERE tournament_id=? AND user_id=?");$s->execute([$id,$winner]);if(!$s->fetch())throw new RuntimeException('Winner must be a participant.');$s=$pdo->prepare("UPDATE tournaments SET status='completed' WHERE id=?");$s->execute([$id]);$s=$pdo->prepare("UPDATE participants SET result=CASE WHEN user_id=? THEN 'Winner' ELSE 'Participated' END WHERE tournament_id=?");$s->execute([$winner,$id]);$s=$pdo->prepare("UPDATE users SET wallet_balance=wallet_balance+? WHERE id=(SELECT user_id FROM participants WHERE tournament_id=? AND user_id=?)");$s->execute([(float)$t['prize_pool'],$id,$winner]);$s=$pdo->prepare("INSERT INTO transactions(user_id,amount,type,description) VALUES(?,?, 'credit',?)");$s->execute([$winner,(float)$t['prize_pool'],'Tournament prize: '.$t['title']]);$pdo->commit();flash('success','Tournament completed and prize credited.');}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();flash('error',$e->getMessage());}}redirect("manage_tournament.php?id=$id");}
$s=$pdo->prepare("SELECT p.*,u.username,u.email FROM participants p JOIN users u ON u.id=p.user_id WHERE p.tournament_id=?");$s->execute([$id]);$parts=$s->fetchAll();$pageTitle='Manage Tournament';require __DIR__.'/common/header.php';
?>
<div class="flex justify-between items-start gap-4"><div><h1 class="text-2xl font-black"><?=e($t['title'])?></h1><p class="text-slate-400"><?=e($t['game_name'])?> · Prize <?=money($t['prize_pool'])?></p></div><span class="px-3 py-1 rounded-full bg-slate-800 text-sm"><?=e($t['status'])?></span></div>
<div class="space-y-3 mt-6"><?php foreach($parts as $p):?><div class="card rounded-xl p-4"><div class="flex justify-between"><div><b><?=e($p['username'])?></b><div class="text-xs text-slate-500"><?=e($p['email'])?></div></div></div><form method="post" class="grid sm:grid-cols-3 gap-2 mt-3"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="rooms"><input type="hidden" name="user_id" value="<?=$p['user_id']?>"><input name="room_id" value="<?=e($p['room_id']??'')?>" placeholder="Room ID" class="bg-slate-900 border border-slate-700 rounded-xl p-2"><input name="room_password" value="<?=e($p['room_password']??'')?>" placeholder="Room Password" class="bg-slate-900 border border-slate-700 rounded-xl p-2"><button class="rounded-xl bg-slate-700">Save Room</button></form></div><?php endforeach;?></div>
<form method="post" class="card rounded-2xl p-5 mt-6"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="tournament_room"><h2 class="text-lg font-bold mb-3">Room Details</h2><div class="grid sm:grid-cols-2 gap-3"><input name="room_id" value="<?=e($t["room_id"]??"")?>" placeholder="Room ID" class="bg-slate-900 border border-slate-700 rounded-xl p-3"><input name="room_password" value="<?=e($t["room_password"]??"")?>" placeholder="Room Password" class="bg-slate-900 border border-slate-700 rounded-xl p-3"></div><button class="mt-3 bg-emerald-600 rounded-xl px-5 py-3 font-bold">Save Room Details</button></form>
<?php if($t["status"]==="upcoming"): ?><form method="post" class="card rounded-2xl p-5 mt-6"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="start"><button class="bg-violet-600 rounded-xl px-5 py-3 font-bold">Start Tournament</button></form><?php endif;?>
<?php require __DIR__.'/common/bottom.php'; ?>
