<?php
require_once __DIR__.'/../common/config.php';require_admin();$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();try{$title=post_string('title');$game=post_string('game_name');$entry=(float)$_POST['entry_fee'];$prize=(float)$_POST['prize_pool'];$time=post_string('match_time');$comm=(float)$_POST['commission'];$room_id=post_string('room_id');$room_password=post_string('room_password');if(!$title||!$game||!$time||$entry<0||$prize<0)throw new RuntimeException('Please fill all fields.');$pdo->prepare("INSERT INTO tournaments(title,game_name,entry_fee,prize_pool,match_time,commission_percentage,status) VALUES(?,?,?,?,?,?,'upcoming')")->execute([$title,$game,$entry,$prize,$time,$comm]);flash('success','Tournament created.');redirect('tournament.php');}catch(Throwable $e){$error=$e->getMessage();}}
if(isset($_GET['delete'])){$pdo->prepare("DELETE FROM tournaments WHERE id=?")->execute([(int)$_GET['delete']]);flash('success','Tournament deleted.');redirect('tournament.php');}
$rows=$pdo->query("SELECT * FROM tournaments ORDER BY match_time DESC")->fetchAll();$pageTitle='Tournaments';require __DIR__.'/common/header.php';
?>
<h1 class="text-2xl font-black mb-5">Create Tournament</h1><?php if($error):?><div class="mb-4 text-rose-300"><?=e($error)?></div><?php endif;?><div class="card rounded-2xl p-5"><form method="post" class="grid md:grid-cols-2 gap-4"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><?php foreach([['title','Title','text'],['game_name','Game Name','text'],['entry_fee','Entry Fee (₹)','number'],['prize_pool','Prize Pool (₹)','number'],['match_time','Match Time','datetime-local'],['commission','Commission %','number'],['room_id','Room ID','text'],['room_password','Room Password','text']] as $f):?><label class="text-sm text-slate-300"><?=$f[1]?><input type="<?=$f[2]?>" name="<?=$f[0]?>" required step="0.01" class="mt-1 w-full rounded-xl bg-slate-900 border border-slate-700 p-3"></label><?php endforeach;?><div class="md:col-span-2"><button class="bg-violet-600 rounded-xl py-3 px-6 font-bold">Create Tournament</button></div></form></div>
<h2 class="text-xl font-bold mt-8 mb-3">Created Tournaments</h2><div class="space-y-3"><?php foreach($rows as $r):?><div class="card rounded-xl p-4 flex flex-wrap gap-3 items-center justify-between"><div><b><?=e($r['title'])?></b><div class="text-sm text-slate-400"><?=e($r['game_name'])?> · <?=money($r['entry_fee'])?> · <?=date('d M Y h:i A',strtotime($r['match_time']))?></div></div><a class="text-violet-300" href="manage_tournament.php?id=<?=$r['id']?>">Manage</a><a class="text-rose-300" href="?delete=<?=$r['id']?>" onclick="return confirm('Delete tournament?')">Delete</a></div><?php endforeach;?></div>
<?php require __DIR__.'/common/bottom.php'; ?>
